---
title: "Compiler Error CS0103 | Microsoft Docs"
ms.custom: ""
ms.date: "11/24/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-csharp"
ms.tgt_pltfrm: ""
ms.topic: "error-reference"
f1_keywords: 
  - "CS0103"
dev_langs: 
  - "CSharp"
helpviewer_keywords: 
  - "CS0103"
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
caps.latest.revision: 13
caps.handback.revision: 13
author: "BillWagner"
ms.author: "wiwagn"
manager: "wpickett"
translationtype: Human Translation
---
# Compiler Error CS0103
[!INCLUDE[vs2017banner](../../../csharp/includes/vs2017banner.md)]

Элемент "identifier" не существует в текущем контексте  
  
 Предпринята попытка использовать элемент, которой не существует в классе, [пространстве имен](../../../csharp/language-reference/keywords/namespace.md) или области действия.  Проверьте правильность написания имени и проверьте директивы using и ссылки на сборки, чтобы убедиться в доступности нужного имени.  
  
 Эта ошибка часто возникает при объявлении переменной в цикле или в блоке `try` или `if`, и при последующей попытке обращения к ней из включающего блока кода или отдельного блока кода, как показано в следующем примере.  
  
```c#  
using System;  
  
class MyClass1  
{  
    public static void Main()  
    {  
        try  
        {  
            // The following declaration is only available inside the try block.  
            MyClass1 conn = new MyClass1();  
        }  
        catch (Exception e)  
        {  
            // The following expression causes error CS0103, because variable  
            // conn only exists in the try block.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
  
```  
  
 В следующем примере разрешена эта ошибка.  
  
```c#  
  
using System;  
  
class MyClass2  
{  
    public static void Main()  
    {  
        // To resolve the error in the example, the first step is to   
        // move the declaration of conn out of the try block. The following  
        // declaration is available throughout the Main method.  
        MyClass2 conn = null;  
        try  
        {  
            // Inside the try block, use the conn variable that you declared  
            // previously.  
            conn = new MyClass2();  
        }  
        catch (Exception e)  
        {  
            // The following expression no longer causes an error, because  
            // the declaration of conn is in scope.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
  
```