---
title: "Compiler Warning (level 1) CS1058 | Microsoft Docs"
ms.custom: ""
ms.date: "11/24/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-csharp"
ms.tgt_pltfrm: ""
ms.topic: "error-reference"
f1_keywords: 
  - "CS1058"
dev_langs: 
  - "CSharp"
helpviewer_keywords: 
  - "CS1058"
ms.assetid: ed50590c-f130-47c3-976d-322a6c8f996d
caps.latest.revision: 11
caps.handback.revision: 11
author: "BillWagner"
ms.author: "wiwagn"
manager: "wpickett"
translationtype: Human Translation
---
# Compiler Warning (level 1) CS1058
[!INCLUDE[vs2017banner](../../../csharp/includes/vs2017banner.md)]

Предыдущее предложение catch уже перехватывает все исключения.Все возникшие исключения будут перенесены в System.Runtime.CompilerServices.RuntimeWrappedException  
  
 Если в блоке `catch()` не задан тип исключения после блока `catch (System.Exception e)`, установка данного атрибута приведет к возникновению ошибки CS1058.  Данное предупреждение не рекомендует перехват исключений блоком `catch()`.  
  
 Блок `catch()`, следующий за блоком `catch (System.Exception e)`, может перехватывать исключения, отличные от CLS, если атрибуту `RuntimeCompatibilityAttribute` задано значение "false" в файле AssemblyInfo.cs: `[assembly: RuntimeCompatibilityAttribute(WrapNonExceptionThrows = false)]`.  Если значение "false" задано неявно, все возникшие не CLS исключения упаковываются как исключения и блок `catch (System.Exception e)` перехватывает их.  Для получения дополнительной информации см. [Практическое руководство. Перехват несовместимого с CLS исключения](../../../csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception.md).  
  
## Пример  
 В следующем примере возникает ошибка CS1058.  
  
```  
// CS1058.cs  
// CS1058 expected  
using System.Runtime.CompilerServices;  
  
// the following attribute is set to true by default in the C# compiler  
// set to false in your source code to resolve CS1058  
[assembly: RuntimeCompatibilityAttribute(WrapNonExceptionThrows = true)]  
  
class TestClass   
{  
   static void Main()   
   {  
      try {}  
  
      catch (System.Exception e) {   
         System. Console.WriteLine("Caught exception {0}", e);  
      }  
  
      catch {}   // CS1058. This line will never be reached.  
   }  
}  
```